version: 2

project_name: clouddns

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: clouddns
    binary: clouddns
    dir: ./cmd/clouddns
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  header: |
    ## goclouddns {{.Tag}}

    This release includes binaries for multiple platforms. Download the appropriate binary for your system.

    ### Installation

    Download the binary for your platform from the assets below, extract it, and add it to your PATH.

    ### Usage

    Set your Rackspace credentials:
    ```bash
    export OS_USERNAME=[username]
    export RAX_API_KEY=[api_key]
    ```

    Then use the CLI:
    ```bash
    clouddns domain list
    clouddns domain create example.com admin@example.com
    clouddns record DOMAIN_ID list
    ```
